version: "3.8"
services:
  postgis:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: streamlit
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
